image : mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo '{}' > src/DammitBot.Console/appsettings.json
    - dotnet build

test:
  stage: test
  script:
    - dotnet test
