image : mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo '{}' > src/DammitBot.Console/appsettings.json
    - dotnet build

test:
  stage: test
  script:
    - 'dotnet test
       --test-adapter-path:.
       --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
       --collect:"XPlat Code Coverage"
       --results-directory cobertura'
    - chmod +x ./scripts/print-test-coverage.sh
    - ./scripts/print-test-coverage.sh cobertura
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
      - cobertura/*/coverage.cobertura.xml
    reports:
      junit:
        - ./**/*test-result.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura/*/coverage.cobertura.xml
