name: dammit_bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '7.0.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Test with dotnet
          run: dotnet test --logger trx
